Arreglado el assigment 4
FacultadInformatica-LinkedData/Curso2023-2024 pull request #105
Opened 2023-11-03 15:48 UTC by victorcamposs220

2023-11-03 16:59 UTC, victorcamposs220 commented
he tenido que realizar otra rama por que como se hizo merge de la anterior con lo que pensaba que estaba todo bien, realice un merge de esta rama con mi rama main. Y debe ser que eso ha producido algo que no he podido manejar y me ha obligado a hacer otra rama.

2023-11-13 16:04 UTC, anaigmo commented on Assignment4/victorcamposs220-210397D/Task07.py
> +  }
there's no restriction avoiding ?Person1 and ?Person2 of being the same

2023-11-13 16:05 UTC, anaigmo commented on Assignment4/victorcamposs220-210397D/Task07.py
tasks 7.1-3 are missing the rdflib option

2023-11-14 15:04 UTC, victorcamposs220 commented
ya pocos cambios puedo hacer ¿Aun con los fallos se tendrá en cuenta, no?

2023-11-14 15:04 UTC, victorcamposs220 commented
digo que puedo hacer pocos a ningún cambio porque la nota se esta ya calculando y saldrá en cuestión de días

2023-11-14 17:01 UTC, anaigmo commented
tienes otra oportunidad para arreglarlo rápido antes de que pongamos la nota definitiva :)

2023-11-14 17:18 UTC, victorcamposs220 commented
Ok. Una pregunta cuando dices que en el 7.1, 7.2 y 7.3 me falata los options de rdflib a que te refieres ?

2023-11-14 20:27 UTC, victorcamposs220 commented
ya están arreglados los errores gracias por las indicaciones

2023-11-15 00:18 UTC, dgarijo requested changes
Very small pending changes

2023-11-15 00:18 UTC, dgarijo commented on Assignment4/victorcamposs220-210397D/Task07.py
> +  }
Missing all the possible subclasses of subclasses. Use the `*` operator

2023-11-15 00:18 UTC, dgarijo commented on Assignment4/victorcamposs220-210397D/Task07.py
> +    {?Subject a ns:Person.} UNION {?SubClass rdf:subClassOf ns:Person. ?Subject a ?SubClass}
same as above

2023-11-15 00:18 UTC, dgarijo commented on Assignment4/victorcamposs220-210397D/Task07.py
> +for s,p,o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
Missing all subclasses of subclasses of living thing. Hint: make the function recursive

2023-11-15 17:46 UTC, victorcamposs220 commented
Hola buenas, ya he hecho los cambios que me dijiste creo que esta todo lo que me mencionaste. Un saludo.

2023-11-15 22:45 UTC, dgarijo commented on Assignment4/victorcamposs220-210397D/Task07.py
> +  print(r.Subject)
Please add exercises 7.4 and 7.5 in rdflib too

2023-11-15 22:45 UTC, dgarijo commented
@victorcamposs220 te faltan los 7.4 y 7.5 en rdflib. Esto no estaba claro en el enunciado pero tambien se requiere.

2023-11-17 08:49 UTC, victorcamposs220 commented
ok

2023-11-17 12:07 UTC, victorcamposs220 commented
Ya esta hecho

2023-11-17 13:04 UTC, merged