assigment 4
FacultadInformatica-LinkedData/Curso2023-2024 pull request #121
Opened 2023-11-15 08:52 UTC by Miguel22hp

2023-11-15 15:48 UTC, dgarijo requested changes

2023-11-15 15:48 UTC, dgarijo commented on Assignment4/Miguel22hp-c200113/task07.py
> +        ?subClass rdfs:subClassOf ns:LivingThing .
This won't retrieve all subclasses of subclasses of Living Thing. You need to use `+`

2023-11-15 15:48 UTC, dgarijo commented on Assignment4/Miguel22hp-c200113/task07.py
> +        FILTER (?class_ = ns:Person || ?class_ = ns:Animal)
this is a very inefficient query. Instead, use UNION

2023-11-15 15:48 UTC, dgarijo commented on Assignment4/Miguel22hp-c200113/task07.py
> +"""
Missing 7.5.
missing exercises with rdflib

2023-11-23 12:53 UTC, anaigmo commented
Entregado con errores sin corregir, no se aceptan más PR

2023-11-23 12:54 UTC, merged