Assignment 4 w140057
FacultadInformatica-LinkedData/Curso2023-2024 pull request #122
Opened 2023-11-15 13:05 UTC by RicTer3637

Added all the changes requested from @anaigmo, created a new pull request due to starting a new branch and the folder changes

2023-11-15 15:31 UTC, dgarijo requested changes
Missing exercises

2023-11-15 15:31 UTC, dgarijo commented on Assignment4/RicTer3637-w140057/task06.py
> +g.add((ns.JohnSmith, VCARD.EmployedAt, ns.UPM))
vcard does not define this property. Either create your own or search for this property in another vocab

2023-11-15 15:31 UTC, dgarijo commented on Assignment4/RicTer3637-w140057/task07.py
> + print(s)
This won't print the subclasses of subclasses of Living thing. Hint: Make the function recursive.

2023-11-15 15:31 UTC, dgarijo commented on Assignment4/RicTer3637-w140057/task07.py
> +    ?subclass rdfs:subClassOf/rdfs:subClassOf* ns:LivingThing.
the operator `*` means 0 or more subclassOf. So what you are writing here is `+` (1 or more). This is not incorrect, but a weird way of stating it.

2023-11-15 15:31 UTC, dgarijo commented on Assignment4/RicTer3637-w140057/task07.py
> +    optional{?subclass rdfs:subClassOf ?subclass.}
You need to use the `*` operator here.

2023-11-15 15:31 UTC, dgarijo commented on Assignment4/RicTer3637-w140057/task07.py
> +         print(sujeto1)
This is not taking into account the individuals of the subclasses of Person

2023-11-15 15:31 UTC, dgarijo commented on Assignment4/RicTer3637-w140057/task07.py
> +    optional{?subclass rdfs:subClassOf ?subclass.}
also this optional is not needed if you use `*`

2023-11-15 15:31 UTC, dgarijo commented on Assignment4/RicTer3637-w140057/task07.py
> +      print(person)
Missing 7.4 and 7.5 in SPARQL

2023-11-15 15:31 UTC, dgarijo commented on Assignment4/RicTer3637-w140057/task07.py
> +for person,p,o in g.triples((None,FOAF.knows,person)):
why do you repeat it twice?

2023-11-15 22:47 UTC, dgarijo commented
Still missing changes on task 7

2023-11-22 13:02 UTC, RicTer3637 commented
Added changes on task 7

2023-11-23 12:52 UTC, anaigmo commented
Entregado con algunos errores sin corregir, no se aceptan más PR

2023-11-23 12:52 UTC, merged