Updated tasks
FacultadInformatica-LinkedData/Curso2023-2024 pull request #124
Opened 2023-11-20 15:35 UTC by patricifrian

2023-11-20 15:57 UTC, dgarijo requested changes
Please address remaining comments

2023-11-20 15:57 UTC, dgarijo commented on Assignment4/patricifrian-190112/task07-updated.py
> +    ?Subject rdfs:subClassOf ns:LivingThing
this does not retrieve all subclasses of subclasses of living thing

2023-11-20 15:57 UTC, dgarijo commented on Assignment4/patricifrian-190112/task07-updated.py
> +    print(s)
same as above

2023-11-20 15:57 UTC, dgarijo commented on Assignment4/patricifrian-190112/task07-updated.py
> +for s, p, o in g.triples((None, rdfs.subClassOf, ns.LivingThing)):
same as below

2023-11-20 15:57 UTC, dgarijo commented on Assignment4/patricifrian-190112/task07-updated.py
> +for r in g.query(q1):
missing last exercise in rdflib

2023-11-21 23:22 UTC, dgarijo requested changes
please address also old issues

2023-11-21 23:22 UTC, dgarijo commented on Assignment4/patricifrian-190112/task07-updated.py
> +    OPTIONAL {?Subclass rdfs:subClassOf ?Subject .}
what about the subclasses of subclasses of subclasses? You need to design a generic query.

2023-11-23 12:49 UTC, anaigmo commented
Entregado con errores sin corregir, no se aceptan más PR

2023-11-23 12:49 UTC, merged