task07
FacultadInformatica-LinkedData/Curso2023-2024 pull request #34
Opened 2023-10-02 17:57 UTC by JorgeMIng

2023-10-30 18:25 UTC, anaigmo commented
You need to merge in one PR this one and #35

2023-11-15 00:23 UTC, dgarijo requested changes
PLease address remaining comments

2023-11-15 00:23 UTC, dgarijo commented on Curso2023-2024/task07.py
> +    print(s)
You are not listing the subclasses of subclasses of living thing

2023-11-15 00:23 UTC, dgarijo commented on Curso2023-2024/task07.py
> +    ?subclass rdfs:subClassOf ns:LivingThing.
same as above. Use the `*` operator

2023-11-15 00:23 UTC, dgarijo commented on Curso2023-2024/task07.py
> +      ?subclass rdfs:subClassOf ns:Person
Almost correct. Use rdf:type/rdfs:subclassOf* to make it fully recursive

2023-11-15 00:23 UTC, dgarijo commented on Curso2023-2024/task07.py
> +
missing 7.5 in sparql

2023-11-23 13:11 UTC, anaigmo commented
Entregado con algún error, no se admiten más PR

2023-11-23 13:12 UTC, merged