Subido Assigment 4
FacultadInformatica-LinkedData/Curso2023-2024 pull request #65
Opened 2023-10-11 17:13 UTC by dcipres

2023-10-30 17:07 UTC, anaigmo commented
You need to change the name of the repo, with your username and student id (`username-id/`). The scripts are looking good, a couple of things:
* task 6.4, you should use the properties that are already in the graph: VCARD.FN, VCARD.Family, VCARD.Given and VCARD.Email
* task 6.5, UPM not defined as type of University

2023-11-17 18:10 UTC, dgarijo requested changes
please address the issues raised in my review

2023-11-17 18:10 UTC, dgarijo commented on Assignment4/z170395-Assigment4/task07.py
> +        ?subclass rdfs:subClassOf <{living_thing}> .
this will not retrieve subclasses of subclasses of living thing. You need to use `*`

2023-11-17 18:10 UTC, dgarijo commented on Assignment4/z170395-Assigment4/task07.py
> +        subclasses.add(s)
Same issue as above. Create a recursive function

2023-11-17 18:10 UTC, dgarijo commented on Assignment4/z170395-Assigment4/task07.py
> +        individuals.add(s)
same issue as above

2023-11-17 18:10 UTC, dgarijo commented on Assignment4/z170395-Assigment4/task07.py
> +            ?individual rdf:type <{person}> .
why don't you add the URI directly in the query?

2023-11-17 18:10 UTC, dgarijo commented on Assignment4/z170395-Assigment4/task07.py
> +   if str(p) == knows and str(o) == rocky :
You have not tested this query. None of the properties are `knows`. They are URIs

2023-11-17 18:10 UTC, dgarijo commented on Assignment4/z170395-Assigment4/task07.py
> +
Missing exercise in sparql

2023-11-23 12:56 UTC, anaigmo commented
Entregado con errores sin corregir, no se aceptan más PR

2023-11-23 12:57 UTC, closed without merging